<?php
/**
 * @file
 * This module provides functions specific to the NUL site.
 *
 * @ingroup nul
 */

function nuliae_footer() {
  $output = '
      <div id="nul-footer">
        <div id="nul-footer-left">';
  $output .= nuliae_nul_logo('footer');
  $output .= '</div><!-- nul-footer-left -->
        <div id="nul-footer-right">';
  $output .= nuliae_iemamp_logo('footer');
  $output .= '
        </div><!-- nul-footer-right -->
  	</div><!-- nul-footer -->';
  return $output;
}

function nuliae_nul_logo($locale) {
  drupal_add_css(drupal_get_path('module', 'nuliae') . '/nuliae.css');
  $output = '
  			<div id="nul_' . $locale . '_nul_logo">
  				<a class="active" title="www.nul.org" href="http://www.nul.org">
            <img alt="nul.org logo" src="/' . drupal_get_path('module', 'nuliae') . '/images/nul_footer_logo.png">
          </a>
        </div> <!-- nul_' . $locale . '_nul_logo -->';
  return $output;
}

function nuliae_iemamp_logo($locale) {
  drupal_add_css(drupal_get_path('module', 'nuliae') . '/nuliae.css');
  $fblink = 'http://facebook.com/National.Urban.League';
  $twlink = 'http://twitter.com/NatUrbanLeague';
  $lilink = 'http://linkedin.com/company/national-urban-league';
  $ytlink = 'http://www.youtube.com/user/IAmEmpoweredVideo';
  $output = '
  			<div id="nul_' . $locale . '_iamemp_logo">
            <a class="active" title="www.iamempowered.com" href="http://www.iamempowered.com">
            <img alt="iamempowered.com logo" src="/' . drupal_get_path('module', 'nuliae') . '/images/iae_logo_community.png">
          </a>
          <ul id="' . $locale . '_map" class="nul_image_map">
            <li><a class="facebook" href="' . $fblink . '" title="Facebook"><span><b>Facebook</b><br>
                Connect with us on Facebook.</span></a></li>

            <li><a class="twitter" href="' . $twlink . '" title="Twitter"><span><b>Twitter</b><br>
                Follow us on Twitter.</span></a></li>

            <li><a class="linkedin" href="' . $lilink . '" title="Linkedin"><span><b>Linkedin</b><br>
                Network with us on Linkedin.</span></a></li>

            <li><a class="youtube" href="' . $ytlink . '" title="YouTube"><span><b>YouTube</b><br>
                See what we&rsquo;re doing on YouTube.</span></a></li>
        	</ul>
        </div> <!-- nul_' . $locale . '_iamemp_logo -->';
  return $output;
}

function nuliae_render_block($menu, $id, $recurse=1, $level = 0) {
  $level++;
  $col = 1;
  $count = 0;
  $total = count($menu);
  $output = '<ul id="' . $id . '">';
  $output .= '<div id="nul_nav_col_' . $col++ . '">';
  foreach ($menu as $item) {
    $link = $item["link"];
    if ($link["hidden"]) {
      continue;
    }
      $class = ' class="first"';
      $nul_id = ' id="' . str_replace(' ', '-', strtolower($link["title"])) . '"';
    //elseif($count == $total){ $class = " class='last'"; }
    //else{ $class = ''; $nul_id = '';}
    $output .= '<li' . $nul_id . $class . '><a href="' . check_url(url($link["href"], $link["options"])) . '">' . $link["title"] . '</a></li>';
    if ($item["below"]) {
      $output .= '<ul id="nul_nav_' . $link['mlid'] . '">';
      foreach ($item["below"] as $level2_item) {
        $class = '';
        $sublink = $level2_item['link'];
        if ($sublink["hidden"]) {
          continue;
        }
        $output .= '<li' . $class . '><a href="' . check_url(url($sublink["href"], $sublink["options"])) . '">' . $sublink["title"] . '</a></li>';
      }
      $output .= '</ul>';
    }
    $count++;
    if ($count % 2 == 0) {
      $output .= '</div>';
      if ($count <= $total) {
        $output .= '<div id="nul_nav_col_' . $col++ . '">';
      }
    }
  }
  $output .= "</ul>";
  return $output;
}//*/

function nuliae_render_menu($menu, $id, $recurse=1, $level = 0) {
  $level++;
  $recurse_limit = 10;
  $count = 1;
  $total = count($menu);
  $output = "<ul id='" . $id . "'>";
  foreach ($menu as $item) {
    $link = $item["link"];
    if ($link["hidden"]) {
      continue;
    }
    if ($recurse == 1 && $count == 1) {
      $class = " class='first'";
      $nul_id = " id='" . str_replace(' ', '-', strtolower($link["title"])) . "'";
    }
    elseif ($count == $total) {
      $class = " class='last'";
    }
    else {
      $class = ''; $nul_id = '';
    }
    $output .= "<li" . $nul_id . $class . "><a href=\"" . check_url(url($link["href"], $link["options"])) . "\">" . $link["title"] . "</a></li>";
    if ($item["below"] && ++$recurse < $recurse_limit) {
      $output .= nuliae_render_block($item["below"], "nul_nav_" . $link['mlid'], $recurse, $level);
    }
    $count++;
  }
  $output .= "</ul>";
  return $output;
}
