<?php

/**
 * @defgroup nul_tophat Top Hat: allowing sso along with common site family branding navigation.
 *
 * Author:  Wes Roepken aka lipcpro < wes at lipcpro dot com >
 * Date:    03/14/2012
 *
 * @file
 * This module provides a standard Tophat menu for NUL sites.
 *
 * @ingroup nul_tophat
 */

function nul_tophat_mobile_permission() {
  return array(
    'tophat mobile login' => array(
      'title' => t("Disallow logins via tophat block"),
      'description' => t('Only check this option to prevent anonymous user to use the login link in the tophat block')
    ),
  );
}

/**
 * Implements hook_block_info()
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function nul_tophat_mobile_block_info()
{
  $block['tophat_mobile'] = array('info' => t('NUL Tophat Mobile block'));
  return $block;
}

/**
 * Implements hook_block_view()
 *
 * @todo Please document this function.
 * @see http://drupal.org/node/1354
 */
function nul_tophat_mobile_block_view($delta = '')
{
 switch ($delta) {
  case 'tophat_mobile':
   $block['subject'] = NULL;
   $block['content'] = theme_nul_tophat_mobile();
   break;
  default:
   $block = array();
   break;
 }
 return $block;
}

/**
 * Implements hook_theme().
 */
function nul_tophat_mobile_theme()
{
 return array(
   'nul_tophat_mobile' => array(
     'render element' => 'block',
   ),
   'nul_tophat_mobile_user_menu_links' => array(
     'variables' => array('links' => NULL),
   ),
 );
}

/**
 * themes the tophat block for the leaderboard region in
 * each of the site's at_site sub theme based on adaptivethemes
 */
function theme_nul_tophat_mobile()
{
 global $user;
 $classes = array();
 drupal_add_css(drupal_get_path('module', 'nul_tophat_mobile') . '/nul_tophat_mobile.css');
 drupal_add_js(drupal_get_path('module', 'nul_tophat_mobile') . '/nul_tophat_mobile.js');
 $nul_tophat_mobile = _nul_mobile_get_links();
 $output = '<div id="tophat-nav-container" class="clearfix">';
 $output .= '
 <div id="tophat-nav">
          <ul id="nul-tophat-sites">
          ';
   /*$j = count($nul_tophat_mobile);*/
   $j = 1;
   for ($i = 0; $i < $j; $i++) {
   if (!$i) {
   $classes[] = 'first';
   }
    if ($i == $j - 1) {
    $classes[] = 'last';
   }
   if (strpos($_SERVER["HTTP_HOST"], $nul_tophat_mobile[$i]['link_title']) !== FALSE && strpos($_SERVER["HTTP_HOST"], $nul_tophat_mobile[$i]['link_title']) == 0) {
     $classes[] = 'active';
   }
   isset($classes) ? $li = '<li id="' . $nul_tophat_mobile[$i]['id'] . '">' : $li = '<li id="' . $nul_tophat_mobile[$i]['id'] . '">';
   $title = $nul_tophat_mobile[$i]['link_title'];
     isset($classes) ? $options = array('attributes' => array('class' => $classes)) : $options = array();
   $output .= $li . l($title, 'http://' . $nul_tophat_mobile[$i]['link_path'], $options) . '</li>
   ';
   unset($classes);
   }
   $output .= '</ul> <!-- "nul-tophat-sites" -->';
 
  /**
   *
   * this isn't working with sso as expected
   * have to find a fix or work around
   */

  if ($user->uid) {
   //$user_fields = user_load($user->uid);
   /*    $u_start = strpos($user->init, '/' , strpos($user->init, 'user'));
   $u_end = strpos($user->init, '/' , ++$u_start);
   $points_user = substr($user->init, $u_start, $u_end - $u_start);
   settype($points_user, 'int');
   $server_url = 'http://stage.iamempowered.com/xmlrpc.php';
   $key = '7c1c13b045136313db0d163e936d8e4b';//array('impact_points' => '7c1c13b045136313db0d163e936d8e4b');
   //$result = xmlrpc($server_url, 'userpoints.get', $key, $uid, $tid);
   $user_points = xmlrpc($server_url, array('userpoints.get' => array($key, $points_user)));
   //$user_points = xmlrpc($server_url, 'userpoints.get', $key, $points_user);
   drupal_set_message(xmlrpc_error_msg());
   dsm(gettype($points_user));
   dsm($user_points);//*/
   $output .= '
   <div id="nul-tophat-user-menu">
   ';
   $output .= '<div class="nul-tophat-user-name">' . $user->name . '</div>';
   $output .= '<div class="nul-tophat-user-link">' . l(t('My Dashboard'), 'dashboard', $options) . '<img src="/' . drupal_get_path('module', 'nul_tophat_mobile') . '/images/user_arrow.jpg" height="8" width="9" class="nul-tophat-arrow" />' . '</div> ' . '<br />';
     $output .= '<div class="nul-tophat-user-link">' . l(t('Logout'), 'user/logout', $options) . '<img src="/' . drupal_get_path('module', 'nul_tophat_mobile') . '/images/user_arrow.jpg" height="8" width="9" class="nul-tophat-arrow" />' . '</div>' . '<br />';
     //$output .= '<div class="nul-tophat-user-points">' . $user_points . '</div>';
    $output .= '
       </div>
       </div>';
   } elseif (!user_access('tophat login')) {
   $output .= '<div id="nul-tophat-user-menu">';
    $output .= '<div class="nul-tophat-user-link">' . l(t('Sign In'), 'user/login', $options) . '<img src="/' . drupal_get_path('module', 'nul_tophat_mobile') . '/images/user_arrow.jpg" height="8" width="9" class="nul-tophat-arrow" />' . '</div>' . '<br />';
      $output .= '<div class="nul-tophat-user-link">' . l(t('Register'), 'user/register') . '<img src="/' . drupal_get_path('module', 'nul_tophat_mobile') . '/images/user_arrow.jpg" height="8" width="9" class="nul-tophat-arrow" />' . '</div>' . '<br />';
        $output .= '</div>';
  } else {
    $output .= '<div id="nul-tophat-user-menu">';
    $output .= '</div>';
    }

    $output .= '</div>';
    $output .= '</div> <!-- "tophat-nav-container" -->';
    return $output;
}


/**
 * Returns HTML for a set of links.
 *
 * from theme.inc theme_links
 *
 * @param $variables
 *   An associative array containing:
 *   - links: An associative array of links to be themed. The key for each link
 *     is used as its CSS class. Each link should be itself an array, with the
 *     following elements:
 *     - title: The link text.
 *     - href: The link URL. If omitted, the 'title' is shown as a plain text
 *       item in the links list.
 *     - html: (optional) Whether or not 'title' is HTML. If set, the title
 *       will not be passed through check_plain().
 *     - attributes: (optional) Attributes for the anchor, or for the <span> tag
 *       used in its place if no 'href' is supplied. If element 'class' is
 *       included, it must be an array of one or more class names.
 *     If the 'href' element is supplied, the entire link array is passed to l()
 *     as its $options parameter.
 *   - attributes: A keyed array of attributes for the UL containing the
 *     list of links.
 *   - heading: (optional) A heading to precede the links. May be an associative
 *     array or a string. If it's an array, it can have the following elements:
 *     - text: The heading text.
 *     - level: The heading level (e.g. 'h2', 'h3').
 *     - class: (optional) An array of the CSS classes for the heading.
 *     When using a string it will be used as the text of the heading and the
 *     level will default to 'h2'. Headings should be used on navigation menus
 *     and any list of links that consistently appears on multiple pages. To
 *     make the heading invisible use the 'element-invisible' CSS class. Do not
 *     use 'display:none', which removes it from screen-readers and assistive
 *     technology. Headings allow screen-reader and keyboard only users to
 *     navigate to or skip the links. See
 *     http://juicystudio.com/article/screen-readers-display-none.php and
 *     http://www.w3.org/TR/WCAG-TECHS/H42.html for more information.
 */
function theme_nul_tophat_mobile_user_menu_links($variables)
{
 $links = $variables['links'];
 $output = '';

 if (count($links) > 0) {
  $output = '';
  $num_links = count($links);
  $i = 2;

  foreach ($links as $key => $link) {
   $output .= '<li class="nul-tophat-user-link">';

   if (isset($link['href'])) {
    // Pass in $link as $options, they share the same keys.
    $output .= l($link['title'], $link['href'], $link);
   }
   $i++;
   $output .= "</li>\n";
  }
 }
 return $output;
}

/**
 * Create the links for NUL specific properties
 *
 */
function _nul_mobile_get_links()
{
 if (strpos($_SERVER["HTTP_HOST"], 'red.nul')) {
  $nul_tophat_mobile = array(
    0 => array('link_title' => 'nul', 'link_path' => 'nul.iamempowered.nul', 'id' => 'nulorg'),
    1 => array('link_title' => 'iae', 'link_path' => 'iamempowered.nul/mobile', 'id' => 'iaecom'),
    2 => array('link_title' => 'conf', 'link_path' => 'conf2013.iamempowered.nul',  'id' => 'conf'),
  );
 } elseif (strpos($_SERVER["HTTP_HOST"], 'stage') !== FALSE) {
  $nul_tophat_mobile  = array(
    0 => array('link_title' => 'nul', 'link_path' => 'nul.stage.iamempowered.com', 'id' => 'nulorg'),
    1 => array('link_title' => 'iae', 'link_path' => 'stage.iamempowered.com/mobile', 'id' => 'iaecom'),
    2 => array('link_title' => 'conf', 'link_path' => 'conf2013.stage.iamempowered.com', 'id' => 'conf'),
  );
 } else {
  $nul_tophat_mobile  = array(
    0 => array('link_title' => 'nul', 'link_path' => 'nul.iamempowered.com', 'id' => 'nulorg'),
    1 => array('link_title' => 'iae', 'link_path' => 'iamempowered.com/mobile', 'id' => 'iaecom'),
    2 => array('link_title' => 'conf', 'link_path' => 'conf2013.iamempowered.com', 'id' => 'conf'),
  );
 }
 return $nul_tophat_mobile;
}
