<?php
/**
 * @file
 * This module provides functions specific to the NUL site.
 *
 * @ingroup nul
 */

/**
 * Implementation of hook_block_info().
 */
function nul_social_mobile_block_info() {
 
  $blocks['social_mobile'] = array('info' =>  t('NUL Social Mobile'));
  
  return $blocks;
}

/**
 * Implementation of hook_block_view().
 */
function nul_social_mobile_block_view($delta = '') {
  switch ($delta) {
 
    case 'social_mobile':
        $block['subject'] = '';
        $block['content'] = nul_social_mobile_banner();
      break;
      default:
       $block = array();
       break;
   
      
      
  }

  return $block;
}


function nul_social_mobile_banner() {
$output = '<div id="nul-social-mobile-banner">';
$output .= nul_social_mobile('secondary');
$output .= '</div><!-- nul-social-banner-->';
return $output;
}

function nul_social_mobile($locale) {

  drupal_add_css(drupal_get_path('module', 'nul_social_mobile') . '/nul_social_mobile.css');
  $fblink = 'http://facebook.com/National.Urban.League';
  $twlink = 'http://twitter.com/NatUrbanLeague';
  $lilink = 'http://linkedin.com/company/national-urban-league';
  $ytlink = 'http://www.youtube.com/user/IAmEmpoweredVideo';
  $rsslink = 'http://nul.iamempowered.com/content/rss-feeds';
  $inslink = 'http://instagram.com/naturbanleague';
  $output = '
  			<div id="nul_' . $locale . '_social_mobile_banner">

  <img alt="iamempowered.com social media" src="/' . drupal_get_path('module', 'nul_social_mobile') . '/images/socialbannerx2.png">           

          <ul id="' . $locale . '_map" class="nul_social_mobile_banner_image_map">
            
              <li><a class="banner-twitter" href="' . $twlink . '" title="Twitter"> </a></li>

                <li><a class="banner-facebook" href="' . $fblink . '" title="Facebook"></a></li>

              <li><a class="banner-linkedin" href="' . $lilink . '" title="Linkedin"> </a></li>

            <li><a class="banner-youtube" href="' . $ytlink . '" title="YouTube"></a></li>
              
            <li><a class="banner-rss" href="' . $rsslink . '" title="RSS"></a></li>
              
             <li><a class="banner-instagram" href="' . $inslink . '" title="Instagram"> </a></li>
        	</ul>
        </div> <!-- nul_' . $locale . '_iamemp_logo -->';
  return $output;
}





